services:
  gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - project-service
      - notification-service
    networks:
      - backend

  auth_db:
    image: postgres:16
    container_name: auth_db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
        - backend


  redis:
    image: redis:7
    container_name: auth_redis
    ports:
      - "6379:6379"
    networks:
        - backend

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth_service
    depends_on:
      auth-migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy 
    ports:
      - "50051:50051"
    networks:
        - backend
  auth-migrate:
    image: migrate/migrate
    volumes:
      - ./auth-service/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://auth_user:password@auth_db:5432/auth_db?sslmode=disable",
      "up"
    ]
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
        - backend
    restart: "no"

  project_db:
    image: postgres:16
    container_name: project_db
    environment:
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project_user -d project_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - project_db_data:/var/lib/postgresql/data
    networks:
        - backend
  project-service:
    build:
      context: .
      dockerfile: project-service/Dockerfile
    container_name: project_service
    depends_on:
      project-migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy 
    ports:
      - "50052:50052"
    networks:
        - backend
  
  project-migrate:
    image: migrate/migrate
    container_name: project_migrate
    volumes:
      - ./project-service/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://project_user:password@project_db:5432/project_db?sslmode=disable",
      "up"
    ]
    depends_on:
      project_db:
        condition: service_healthy
    networks:
      - backend
    restart: "no"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  analytics-service:
    build:
      context: .
      dockerfile: analytics-service/Dockerfile
    container_name: analytics_service
    depends_on:
      project-migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy 
    ports:
      - "50053:50053"
    networks:
        - backend
  analytics_db:
    image: postgres:16
    container_name: analytics_db
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics_user -d analytics_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - analytics_db_data:/var/lib/postgresql/data
    networks:
        - backend
    
  analytics-migrate:
    image: migrate/migrate
    container_name: analytics_migrate
    volumes:
      - ./analytics-service/migrations:/migrations
    command: [
        "-path", "/migrations",
        "-database", "postgres://analytics_user:password@analytics_db:5432/analytics_db?sslmode=disable",
        "up"
      ]
    depends_on:
      analytics_db:
        condition: service_healthy
    networks:
      - backend
    restart: "no"

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification_service
    depends_on:
      notification-migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    ports:
      - "50054:50054"
    networks:
      - backend

  notification_db:
    image: postgres:16
    container_name: notification_db
    environment:
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification_user -d notification_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    networks:
      - backend

  notification-migrate:
    image: migrate/migrate
    container_name: notification_migrate
    volumes:
      - ./notification-service/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://notification_user:password@notification_db:5432/notification_db?sslmode=disable",
      "up"
    ]
    depends_on:
      notification_db:
        condition: service_healthy
    networks:
      - backend
    restart: "no"

volumes:
  auth_db_data:
  project_db_data:
  analytics_db_data:
  notification_db_data:

networks:
    backend:
      driver: bridge